#puerto de la aplicacion 
server:
  port: 5500
  address: 0.0.0.0

# Configuracion  de  la aplicacion  
spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: baseapp
  profiles:
    active: dev  # Cambia esto según el entorno: dev, qa, prod
  #Configuración de la base de datos MySQL
  datasource:
    username: sa
    password: Tecs2024*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  # Configuración de la seguridad de la aplicación
  security:
    enabled: false
    user:
     name: user
     password: $2a$12$od1exy/dPLCsL3yxbJeFcO/AxDCKyYVBjl/bGB.7GgM3aGOWeWc.q
     #configuracion email - del servidor SMTP   
  mail:
    host: smtp.gmail.com
    port: 587
    username: desarrollador9tecsersas@gmail.com
    password: nryjjckrqzxmrjuc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  # Clave secreta JWT
jwt:
   secret:
    key: "U6w3yjuQRNWNRG3IaajKZY8nyMPiu+wFLpj/7evdNEc="  
  # Configuración de la consola de la base de datos
logging:
  level:
       "[org.hibernate.SQL]": debug

  
    
